
stages:
  - build_and_push

default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker info

variables:
  DOCKER_IMAGE_NAME: studio98s/leaderboard-api
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

build_push_release:
  stage: build_and_push

  before_script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login docker.io -u $DOCKER_HUB_USER --password-stdin

  script:
    - docker build -t "${DOCKER_IMAGE_NAME}:${CI_COMMIT_TAG}" .
    - docker tag "${DOCKER_IMAGE_NAME}:${CI_COMMIT_TAG}" "${DOCKER_IMAGE_NAME}:latest"
    - docker push "${DOCKER_IMAGE_NAME}:${CI_COMMIT_TAG}"
    - docker push "${DOCKER_IMAGE_NAME}:latest"

  rules:
    - if: $CI_COMMIT_TAG

  after_script:
    - docker logout docker.io || true

build_push_gitlab:
  stage: build_and_push

  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin

  script:
    - GITLAB_IMAGE_COMMIT_TAGGED="${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"
    - GITLAB_IMAGE_LATEST="${CI_REGISTRY_IMAGE}:latest"
    - docker build -t "${GITLAB_IMAGE_COMMIT_TAGGED}" .
    - docker tag "${GITLAB_IMAGE_COMMIT_TAGGED}" "${GITLAB_IMAGE_LATEST}"
    - docker push "${GITLAB_IMAGE_COMMIT_TAGGED}"
    - docker push "${GITLAB_IMAGE_LATEST}"

  rules:
    - if: $CI_COMMIT_BRANCH == "master" && $CI_COMMIT_TAG == null

  after_script:
    - docker logout $CI_REGISTRY || true
