# fly.toml app configuration file generated for Leaderboard on 2025-04-12T19:34:38+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'Leaderboard'
primary_region = 'cdg'

[build]
  dockerfile = "Dockerfile"

[env]
  ASPNETCORE_ENVIRONMENT = "Production"
  ASPNETCORE_URLS = "http://+:8080"
  ConnectionString = "mongodb://Leaderboard-db.internal:27017/LeaderboardDb"
  LeaderboardDb = "LeaderboardDb"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
